language: node_js
node_js:
  - "6"
before_script:
  - cp config.js.dist config.js
script: npm run build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ricki-z"
  - git config --local user.email "ricki_z@gmx.de"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  script: npm run build
  skip_cleanup: true
  on:
    tags: true
